#### 1. 데이터 로드

In [34]:
from sklearn.datasets import load_iris

In [35]:
iris_data = load_iris()

In [36]:
type(iris_data)

sklearn.utils.Bunch

In [37]:
iris_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [38]:
print(iris_data['data'].shape)
iris_data['data'][:10]

(150, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [39]:
iris_data['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [40]:
print(iris_data['target'].shape)
iris_data['target']

(150,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
iris_data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [42]:
#Bunch 객체를 DataFrame 객체로 변환하기
import pandas as pd

df = pd.DataFrame(iris_data['data'], columns=iris_data['feature_names'])

In [43]:
print(df.shape)
print(df.info())
df.head()

(150, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
dtypes: float64(4)
memory usage: 4.8 KB
None


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [44]:
# target 이라는 컬럼 생성
df['target'] = iris_data['target']
df['target'].value_counts()

2    50
1    50
0    50
Name: target, dtype: int64

In [45]:
#label 컬럼을 생성
print(dict(enumerate(iris_data['target_names'])))
df['label'] = df.target.replace(dict(enumerate(iris_data['target_names'])))
df.head()

{0: 'setosa', 1: 'versicolor', 2: 'virginica'}


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target   label  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [46]:
df['label'].value_counts()

virginica     50
setosa        50
versicolor    50
Name: label, dtype: int64

In [47]:
df.iloc[ : , 0:4 ].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

#### 2. 훈련데이터와 테스트데이터 나누기
* 훈련데이터(train data)는 학습을 할때 사용되는 데이터 (머신러닝 모델을 만들때 사용)
* 테스트데이터(test data)는 예측을 할때 사용되는 데이터(모델이 얼마나 잘 동작하는지 측정할때 사용)
* 수학함수에서 f(x) = y, x는 입력, y는 출력
* 훈련데이터의 값(X_train) , 훈련데이터의 레이블 (y_train)
* 테스트데이터의 값(X_test), 테스트데이터의 레이블(y_test)
* 75%는 훈련데이터, 25%는 테스트 데이터
* train_test_split() 함수사용

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(\
                                         df.iloc[ : , 0:4 ], df['target'],
                                                    random_state = 71)

In [50]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(112, 4) (112,)
(38, 4) (38,)


#### 3. 학습하기(fit) & 예측하기(predict) & 평가하기(score)

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
model = KNeighborsClassifier(n_neighbors=5, weights='distance')
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

In [53]:
#학습하기
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='distance')

In [54]:
# 예측하기
predictions = model.predict(X_test)
predictions

array([2, 0, 1, 2, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 1, 0])

In [57]:
# 평가하기
import numpy as np

print('테스트 세트의 정확도 {:.2f}'.format(np.mean(predictions == y_test)))
print('테스트 세트의 정확도 {:.2f}'.format(model.score(X_test, y_test)))

테스트 세트의 정확도 0.97
테스트 세트의 정확도 0.97
